import "../globals.css";
import Header from "../Component/header";
import Footer from "../Component/Footer";
import { Asap } from 'next/font/google';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const asap = Asap({
  subsets: ['latin'],
  weights: ['400', '700'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={asap.className}>

        <main className="py-4">
          <Header />
          {children}
          <Footer />
        </main>

      </body>
    </html>
  );
}
